while wait() do
rconsolename("Arson's Link Encrypter")
rconsoleprint("Enter your link:\n\n")
local INPUT = rconsoleinput()
local encStr1 = {}
local the_string = INPUT
local length = #the_string 
for i = 1,length+1 do  
    local chara = string.sub(the_string, i, i)
    if chara == "a" then table.insert(encStr1,"%61")
    elseif chara == "b" then table.insert(encStr1,"%62")
    elseif chara == "c" then table.insert(encStr1,"%63")
    elseif chara == "d" then table.insert(encStr1,"%64")
    elseif chara == "e" then table.insert(encStr1,"%65")
    elseif chara == "f" then table.insert(encStr1,"%66")
    elseif chara == "g" then table.insert(encStr1,"%67")
    elseif chara == "h" then table.insert(encStr1,"%68")
    elseif chara == "i" then table.insert(encStr1,"%69")
    elseif chara == "j" then table.insert(encStr1,"%6A")
    elseif chara == "k" then table.insert(encStr1,"%6B")
    elseif chara == "l" then table.insert(encStr1,"%6C")
    elseif chara == "m" then table.insert(encStr1,"%6D")
    elseif chara == "n" then table.insert(encStr1,"%6E")
    elseif chara == "o" then table.insert(encStr1,"%6F")
    elseif chara == "p" then table.insert(encStr1,"%70")
    elseif chara == "q" then table.insert(encStr1,"%71")
    elseif chara == "r" then table.insert(encStr1,"%72")
    elseif chara == "s" then table.insert(encStr1,"%73")
    elseif chara == "t" then table.insert(encStr1,"%74")
    elseif chara == "u" then table.insert(encStr1,"%75")
    elseif chara == "v" then table.insert(encStr1,"%76")
    elseif chara == "w" then table.insert(encStr1,"%77")
    elseif chara == "x" then table.insert(encStr1,"%78")
    elseif chara == "y" then table.insert(encStr1,"%79")
    elseif chara == "z" then table.insert(encStr1,"%7A")
    elseif chara == "A" then table.insert(encStr1,"%41")
    elseif chara == "B" then table.insert(encStr1,"%42")
    elseif chara == "C" then table.insert(encStr1,"%43")
    elseif chara == "D" then table.insert(encStr1,"%44")
    elseif chara == "E" then table.insert(encStr1,"%45")
    elseif chara == "F" then table.insert(encStr1,"%46")
    elseif chara == "G" then table.insert(encStr1,"%47")
    elseif chara == "H" then table.insert(encStr1,"%48")
    elseif chara == "I" then table.insert(encStr1,"%49")
    elseif chara == "J" then table.insert(encStr1,"%4A")
    elseif chara == "K" then table.insert(encStr1,"%4B")
    elseif chara == "L" then table.insert(encStr1,"%4C")
    elseif chara == "M" then table.insert(encStr1,"%4D")
    elseif chara == "N" then table.insert(encStr1,"%4E")
    elseif chara == "O" then table.insert(encStr1,"%4F")
    elseif chara == "P" then table.insert(encStr1,"%50")
    elseif chara == "Q" then table.insert(encStr1,"%51")
    elseif chara == "R" then table.insert(encStr1,"%52")
    elseif chara == "S" then table.insert(encStr1,"%53")
    elseif chara == "T" then table.insert(encStr1,"%54")
    elseif chara == "U" then table.insert(encStr1,"%55")
    elseif chara == "V" then table.insert(encStr1,"%56")
    elseif chara == "W" then table.insert(encStr1,"%57")
    elseif chara == "X" then table.insert(encStr1,"%58")
    elseif chara == "Y" then table.insert(encStr1,"%59")
    elseif chara == "Z" then table.insert(encStr1,"%5A")
    elseif chara == "1" then table.insert(encStr1,"%31")
    elseif chara == "2" then table.insert(encStr1,"%32")
    elseif chara == "3" then table.insert(encStr1,"%33")
    elseif chara == "4" then table.insert(encStr1,"%34")
    elseif chara == "5" then table.insert(encStr1,"%35")
    elseif chara == "6" then table.insert(encStr1,"%36")
    elseif chara == "7" then table.insert(encStr1,"%37")
    elseif chara == "8" then table.insert(encStr1,"%38")
    elseif chara == "9" then table.insert(encStr1,"%39")
    elseif chara == "0" then table.insert(encStr1,"%30")
    else table.insert(encStr1,chara)
    end
end
rconsoleprint(table.concat(encStr1))
rconsoleprint("\n\n\n")
end
